version: '3.5'

services:

  api01:
    restart: unless-stopped
    hostname: api01
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    environment:
      - CONN_URL=postgresql+pycopg2://admin:123@localhost:5433/rinha
      - DB_HOST=localhost
      - DB_USER=admin
      - DB_PASSWORD=rinha
      - DB_NAME=rinhabackenddb
      - DB_PORT=5433
      - PORT=8001
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  api02:
    restart: unless-stopped
    hostname: api02
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
    ports:
      - "8002:8002"
    environment:
      - CONN_URL=postgresql+pycopg2://admin:123@localhost:5433/rinha
      - DB_HOST=localhost
      - DB_USER=admin
      - DB_PASSWORD=rinha
      - DB_NAME=rinhabackenddb
      - DB_PORT=5433
      - PORT=8002
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"


  nginx:
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    restart: unless-stopped
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5433:5433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"


networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1


