# QUE SE FODA ESSE CONTAINER DE BOSTA POR ENQUANTO
version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_INITIAL_POOL_SIZE=13
      - DB_MAX_POOL_SIZE=13
      - API_USE_DB_FUNC=true
      - PORT=8000 
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host=0.0.0.0 --port=8000

    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8001:8000"
    command: uvicorn main:app --reload --host=0.0.0.0 --port=8001

    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5433:5433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1